import pygame

CELLSIZE = 40
CELLNUMBER = 20
SCREENWIDTH = CELLSIZE*CELLNUMBER
SCREENHEIGHT = CELLSIZE*CELLNUMBER


SCREEN = pygame.display.set_mode((SCREENWIDTH, SCREENHEIGHT))
CLOCK = pygame.time.Clock()
FPS = 60

SCREEN_UPDATE = pygame.USEREVENT
pygame.time.set_timer(SCREEN_UPDATE,150)